
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

EventScript_DebugPack::
	lockall
	setflag FLAG_SYS_POKEMON_GET
	setflag FLAG_SYS_POKEDEX_GET
	setflag FLAG_SYS_POKENAV_GET
	setflag FLAG_SYS_B_DASH
	setflag FLAG_RECEIVED_RUNNING_SHOES
	setflag FLAG_RECEIVED_AMULET_COIN
	setflag FLAG_SYS_ENABLE_DEBUG_MENU
	setflag FLAG_IS_CHAMPION
	special EnableNationalPokedex
	givemon SPECIES_CHARIZARD, 100, 0
	givemon SPECIES_BLASTOISE, 100, 0
	givemon SPECIES_VENUSAUR, 100, 0
	givemon SPECIES_SNORLAX, 100, 0
	additem ITEM_AMULET_COIN, 1
	additem ITEM_RARE_CANDY, 99
	additem ITEM_MASTER_BALL, 99
	additem ITEM_TM01_FOCUS_PUNCH, 99
	additem ITEM_TM02_DRAGON_CLAW, 99
	additem ITEM_TM03_WATER_PULSE, 99
	additem ITEM_TM04_CALM_MIND, 99
	additem ITEM_TM05_ROAR, 99
	additem ITEM_TM06_TOXIC, 99
	additem ITEM_TM07_HAIL, 99
	additem ITEM_TM08_BULK_UP, 99
	additem ITEM_TM09_BULLET_SEED, 99
	additem ITEM_TM10_HIDDEN_POWER, 99
	additem ITEM_TM11_SUNNY_DAY, 99
	additem ITEM_TM12_TAUNT, 99
	additem ITEM_TM13_ICE_BEAM, 99
	additem ITEM_TM14_BLIZZARD, 99
	additem ITEM_TM15_HYPER_BEAM, 99
	additem ITEM_TM16_LIGHT_SCREEN, 99
	additem ITEM_TM17_PROTECT, 99
	additem ITEM_TM18_RAIN_DANCE, 99
	additem ITEM_TM19_GIGA_DRAIN, 99
	additem ITEM_TM20_SAFEGUARD, 99
	additem ITEM_TM21_FRUSTRATION, 99
	additem ITEM_TM22_SOLARBEAM, 99
	additem ITEM_TM23_IRON_TAIL, 99
	additem ITEM_TM24_THUNDERBOLT, 99
	additem ITEM_TM25_THUNDER, 99
	additem ITEM_TM26_EARTHQUAKE, 99
	additem ITEM_TM27_RETURN, 99
	additem ITEM_TM28_DIG, 99
	additem ITEM_TM29_PSYCHIC, 99
	additem ITEM_TM30_SHADOW_BALL, 99
	additem ITEM_TM31_BRICK_BREAK, 99
	additem ITEM_TM32_DOUBLE_TEAM, 99
	additem ITEM_TM33_REFLECT, 99
	additem ITEM_TM34_SLUDGE_WAVE, 99
	additem ITEM_TM35_FLAMETHROWER, 99
	additem ITEM_TM36_SLUDGE_BOMB, 99
	additem ITEM_TM37_SANDSTORM, 99
	additem ITEM_TM38_FIRE_BLAST, 99
	additem ITEM_TM39_ROCK_TOMB, 99
	additem ITEM_TM40_AERIAL_ACE, 99
	additem ITEM_TM41_TORMENT, 99
	additem ITEM_TM42_FACADE, 99
	additem ITEM_TM43_SECRET_POWER, 99
	additem ITEM_TM44_REST, 99
	additem ITEM_TM45_ATTRACT, 99
	additem ITEM_TM46_THIEF, 99
	additem ITEM_TM47_STEEL_WING, 99
	additem ITEM_TM48_SKILL_SWAP, 99
	additem ITEM_TM49_SLEEP_TALK, 99
	additem ITEM_TM50_OVERHEAT, 99
	additem ITEM_TM51_ROOST, 99
	additem ITEM_TM52_FOCUS_BLAST, 99
	additem ITEM_TM53_ENERGY_BALL, 99
	additem ITEM_TM54_PSYSHOCK, 99
	additem ITEM_TM55_SCALD, 99
	additem ITEM_TM56_LEECH_LIFE, 99
	additem ITEM_TM57_CHARGE_BEAM, 99
	additem ITEM_TM58_ENDURE, 99
	additem ITEM_TM59_DRAGON_PULSE, 99
	additem ITEM_TM60_DRAIN_PUNCH, 99
	additem ITEM_TM61_WILL_O_WISP, 99
	additem ITEM_TM62_ACROBATICS, 99
	additem ITEM_TM63_ROCK_SLIDE, 99
	additem ITEM_TM64_EXPLOSION, 99
	additem ITEM_TM65_SHADOW_CLAW, 99
	additem ITEM_TM66_PAYBACK, 99
	additem ITEM_TM67_RECYCLE, 99
	additem ITEM_TM68_GIGA_IMPACT, 99
	additem ITEM_TM69_ROCK_POLISH, 99
	additem ITEM_TM70_AURORA_VEIL, 99
	additem ITEM_TM71_STONE_EDGE, 99
	additem ITEM_TM72_VOLT_SWITCH, 99
	additem ITEM_TM73_THUNDER_WAVE, 99
	additem ITEM_TM74_GYRO_BALL, 99
	additem ITEM_TM75_SWORDS_DANCE, 99
	additem ITEM_TM76_STEALTH_ROCK, 99
	additem ITEM_TM77_STRUGGLE_BUG, 99
	additem ITEM_TM78_BULLDOZE, 99
	additem ITEM_TM79_FREEZE_DRY, 99
	additem ITEM_TM80_VENOSHOCK, 99
	additem ITEM_TM81_X_SCISSOR, 99
	additem ITEM_TM82_DRAGON_TAIL, 99
	additem ITEM_TM83_FLAME_CHARGE, 99
	additem ITEM_TM84_POISON_JAB, 99
	additem ITEM_TM85_DREAM_EATER, 99
	additem ITEM_TM86_GRASS_KNOT, 99
	additem ITEM_TM87_SMACK_DOWN, 99
	additem ITEM_TM88_LOW_SWEEP, 99
	additem ITEM_TM89_U_TURN, 99
	additem ITEM_TM90_SUBSTITUTE, 99
	additem ITEM_TM91_FLASH_CANNON, 99
	additem ITEM_TM92_TRICK_ROOM, 99
	additem ITEM_TM93_WILD_CHARGE, 99
	additem ITEM_TM94_SUCKER_PUNCH, 99
	additem ITEM_TM95_SNARL, 99
	additem ITEM_TM96_AVALANCHE, 99
	additem ITEM_TM97_DARK_PULSE, 99
	additem ITEM_TM98_FALSE_SWIPE, 99
	additem ITEM_TM99_DAZZLING_GLEAM, 99
	additem ITEM_TM100_CURSE, 99
	additem ITEM_HM01_CUT, 99
	additem ITEM_HM02_FLY, 99
	additem ITEM_HM03_SURF, 99
	additem ITEM_HM04_STRENGTH, 99
	additem ITEM_HM05_FLASH, 99
	additem ITEM_HM06_ROCK_SMASH, 99
	additem ITEM_HM07_WATERFALL, 99
	additem ITEM_HM08_DIVE, 99
	additem ITEM_EXP_SHARE, 1
	additem ITEM_GOOD_ROD, 1
	additem ITEM_MACH_BIKE, 1
	setflag FLAG_BADGE01_GET
	setflag FLAG_BADGE02_GET
	setflag FLAG_BADGE03_GET
	setflag FLAG_BADGE04_GET
	setflag FLAG_BADGE05_GET
	setflag FLAG_BADGE06_GET
	setflag FLAG_BADGE07_GET
	setflag FLAG_BADGE08_GET
	releaseall
	end

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

EventScript_CheckSavefileSize::
	special CheckSavefileSize
	msgbox EventScript_Text_CheckSavefileSize
	release
	end

EventScript_Text_CheckSavefileSize:
	.string "SaveBlock1 size: {STR_VAR_1}/15752 bytes.\nSaveBlock2 size: {STR_VAR_2}/3884 bytes.\p{PKMN}Storage size: {STR_VAR_3}/33744 bytes.$"

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

EventScript_CheckEVs::
	lockall
	faceplayer
	getpartysize
	compare VAR_RESULT, 0
	goto_if_eq EventScript_NoPokemon
	special ChoosePartyMon
	waitstate
	compare VAR_0x8004, PARTY_SIZE
	goto_if_ge EventScript_Cancel
	specialvar VAR_RESULT, ScriptGetPartyMonSpecies
	compare VAR_RESULT, SPECIES_EGG
	goto_if_eq EventScript_CheckEVs_Egg
	special CheckMonOffensiveEVs
	msgbox EventScript_CheckEVs_Text_Evaluation
	special CheckMonDefensiveEVs
	msgbox EventScript_CheckEVs_Text_Evaluation2
	releaseall
	end

EventScript_Cancel:
	lockall
	faceplayer
	releaseall
	end

EventScript_CheckEVs_Egg:
	lockall
	faceplayer
	msgbox EventScript_CheckEVs_Text_Egg
	releaseall
	end

EventScript_NoPokemon:
	msgbox EventScript_Text_NoPokemon
	releaseall
	end

EventScript_CheckEVs_Text_Evaluation:
	.string "Your POKéMON has: {STR_VAR_1} ATK EVs,\n"
	.string "{STR_VAR_2} SPD EVs and {STR_VAR_3} SP. ATK. EVs.$"

EventScript_CheckEVs_Text_Evaluation2:
	.string "It also has: {STR_VAR_1} HP EVs,\n"
	.string "{STR_VAR_2} DEF EVs and {STR_VAR_3} SP. DEF. EVs.$"

EventScript_CheckEVs_Text_Egg:
	.string "Sorry, Pokémon Eggs don't\n"
	.string "have EVs.$"

EventScript_Text_NoPokemon:
	.string "You don't have a Pokémon!$"

EventScript_Text_ComeBackAnytime:
	.string "Come back anytime.$"

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

EventScript_CheckIVs::
	lockall
	faceplayer
	getpartysize
	compare VAR_RESULT, 0
	goto_if_eq EventScript_NoPokemon
	special ChoosePartyMon
	waitstate
	compare VAR_0x8004, PARTY_SIZE
	goto_if_ge EventScript_Cancel
	specialvar VAR_RESULT, ScriptGetPartyMonSpecies
	compare VAR_RESULT, SPECIES_EGG
	goto_if_eq EventScript_CheckIVs_Egg
	special CheckMonOffensiveIVs
	msgbox EventScript_CheckIVs_Text_Evaluation
	special CheckMonDefensiveIVs
	msgbox EventScript_CheckIVs_Text_Evaluation2
	releaseall
	end

EventScript_CheckIVs_Egg:
	lockall
	faceplayer
	msgbox EventScript_CheckIVs_Text_Egg
	releaseall
	end

EventScript_CheckIVs_Text_Evaluation:
	.string "Your POKéMON has: {STR_VAR_1} ATK IVs,\n"
	.string "{STR_VAR_2} SPD IVs and {STR_VAR_3} SP. ATK. IVs.$"

EventScript_CheckIVs_Text_Evaluation2:
	.string "It also has: {STR_VAR_1} HP IVs,\n"
	.string "{STR_VAR_2} DEF IVs and {STR_VAR_3} SP. DEF. IVs.$"

EventScript_CheckIVs_Text_Egg:
	.string "Sorry, Pokémon Eggs don't\n"
	.string "have IVs.$"

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

EventScript_ForceEggHatch::
	lockall
	getpartysize
	compare VAR_RESULT, 0
	goto_if_eq EventScript_NoPokemon
	special ChoosePartyMon
	waitstate
	compare VAR_0x8004, PARTY_SIZE
	goto_if_ge EventScript_Cancel
	specialvar VAR_RESULT, ScriptGetPartyMonSpecies
	compare VAR_RESULT, SPECIES_EGG
	goto_if_ne EventScript_Cancel
	special EggHatch
	waitstate
	releaseall
	end

EventScript_ForcedEggHatch_Text_NotAnEgg:
	.string "That's not a Pokémon Egg.$"

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@


EventScript_Inclement_Difficulty::
	lockall
	faceplayer
	msgbox EventScript_Inclement_Difficulty_Text
	releaseall
	end

EventScript_Inclement_Difficulty_Text:
.string "Difficulty: {STR_VAR_1}          \nLevel Cap: {STR_VAR_2}$"
